### ISSUE TITLE
[03-30-2023 23:09:31][Warning]Admin does not have the proper permissions for this function. Please return to Main Menu!

### ISSUE THREAD

**Issue by braydenanderson2014** [braydenanderson2014/Solar-Rental#10]
**Describe the bug**
[03-30-2023 23:09:31][Warning]Admin does not have the proper permissions for this function. Please return to Main Menu! 
(AdministratorFunctions)
issue appears to be random. Issue occurs after succesfully updating certain items such as the tax value.

**Expected behavior**
No Error should be generating

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by braydenanderson2014** [comment]
[Error]:  [2023-08-26T22:42:38.031826700] java.lang.NumberFormatException: Cannot parse null string [E1T0][0m
[0;33m[Warning]:  [2023-08-26T22:42:38.031826700] An Error Occured with the Administrative Menu... Reloading Menu[0m
[0;36m[Debug]:  [2023-08-26T22:42:38.034802200] java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at MainSystem.AdministrativeFunctions.AdministrativeMenu(AdministrativeFunctions.java:454)
	at MainSystem.AdministrativeFunctions.AdministrativeMenu(AdministrativeFunctions.java:384)
	at MainSystem.MainMenu.mainMenu(MainMenu.java:72)
	at Login.Login.loginScreen(Login.java:249)
	at InstallManager.ProgramController.Start(ProgramController.java:54)
	at MainSystem.Main.start(Main.java:96)
	at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@20.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@20.0.1/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@20.0.1/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:833)
[0m
[0;36m[Debug]:  [2023-08-26T22:42:38.035802] MainSystem.RequestLoader$RequestData@342141ac[0m
[0;36m[Debug]:  [2023-08-26T22:42:38.037797500] MainSystem.RequestLoader$RequestData@2fb6450[0m
