### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0 [Admin Requests]

### ISSUE THREAD

**Issue by braydenanderson2014** [braydenanderson2014/Solar-Rental#15]
Issue seems to be occurring only when admin selects the request they want to work on. The error is thrown once the request is selected and displayed.

**Comment by braydenanderson2014** [comment]
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:893)
	at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.remove(ArrayList.java:504)
	at MainSystem.RequestLoader.removeRequestByID(RequestLoader.java:177)
	at MainSystem.AdministrativeFunctions.resolutionAdvisory(AdministrativeFunctions.java:625)
	at MainSystem.Settings.settingsMenu(Settings.java:324)
	at MainSystem.Settings.settingsMenu(Settings.java:387)
	at UserController.MaintainUserController.updateProfileSettings(MaintainUserController.java:379)
	at UserController.MaintainUserController.updateProfileSettings(MaintainUserController.java:349)
	at MainSystem.Settings.settingsMenu(Settings.java:295)
	at MainSystem.MainMenu.mainMenu(MainMenu.java:92)
	at Login.Login.loginScreen(Login.java:249)
	at InstallManager.ProgramController.Start(ProgramController.java:54)
	at MainSystem.Main.start(Main.java:96)
	at javafx.graphics@20.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@20.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@20.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@20.0.1/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@20.0.1/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	... 1 more
Exception running application MainSystem.Main

**Comment by braydenanderson2014** [comment]
Reading this stacktrace, issue actually appears to be with the removeRequestByID method in RequestLoader and not with Administrative Functions class

**Comment by braydenanderson2014** [comment]
Issue is solved, Next Release will have the fix. Getting ready to release the update.
